name: mix-me
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==1.0.0
      - alabaster==0.7.13
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.0
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - binaryornot==0.4.4
      - bleach==6.0.0
      - brax==0.10.3
      - certifi==2023.5.7
      - cffi==1.15.1
      - cfgv==3.3.1
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - chex==0.1.86
      - click==8.1.3
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - comm==0.1.3
      - commonmark==0.9.1
      - contourpy==1.0.7
      - cookiecutter==2.1.1
      - cycler==0.11.0
      - dataclasses==0.6
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distlib==0.3.6
      - dm-env==1.6
      - dm-haiku==0.0.5
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docutils==0.18.1
      - esquilax==2.1.0
      - etils==1.3.0
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastjsonschema==2.17.1
      - filelock==3.12.2
      - flake8==6.0.0
      - flask==2.2.5
      - flask-cors==6.0.1
      - flax==0.8.5
      - fonttools==4.39.4
      - fqdn==1.5.1
      - fsspec==2025.5.1
      - gast==0.5.4
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.5.9
      - grpcio==1.54.2
      - gym==0.23.1
      - gym-notices==0.0.8
      - gymnasium==1.1.0
      - gymnasium-robotics==1.3.1
      - gymnax==0.0.9
      - hf-xet==1.1.5
      - huggingface-hub==0.33.2
      - humanize==4.12.3
      - hydra-core==1.3.2
      - identify==2.5.24
      - idna==3.4
      - imageio==2.31.0
      - imagesize==1.4.1
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - ipykernel==6.23.1
      - ipympl==0.9.3
      - ipython==8.12.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - isort==5.12.0
      - itsdangerous==2.2.0
      - jax==0.4.28
      - jax-cuda12-pjrt==0.4.28
      - jax-cuda12-plugin==0.4.28
      - jax-tqdm==0.4.0
      - jaxlib==0.4.28
      - jaxmarl==0.0.7
      - jaxopt==0.8.5
      - jedi==0.18.2
      - jinja2==3.0.3
      - jinja2-time==0.2.0
      - jmp==0.0.4
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jumanji==0.3.1
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==2.0.5
      - ml-collections==1.1.0
      - ml-dtypes==0.5.1
      - msgpack==1.0.5
      - mujoco==3.1.3
      - mujoco-mjx==3.0.0
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.9.0
      - nest-asyncio==1.5.6
      - nodeenv==1.8.0
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.1
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==8.9.7.29
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - optax==0.1.9
      - orbax-checkpoint==0.6.4
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pettingzoo==1.23.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.5.1
      - pre-commit==3.3.3
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.38
      - protobuf==3.19.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycodestyle==2.10.0
      - pycparser==2.21
      - pyflakes==3.0.1
      - pygame==2.4.0
      - pygments==2.15.1
      - pyopengl==3.1.7
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-slugify==8.0.1
      - pytinyrenderer==0.0.14
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==25.1.0
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==11.2.0
      - safetensors==0.5.3
      - scikit-learn==1.0.2
      - scipy==1.9.0
      - seaborn==0.11.2
      - send2trash==1.8.2
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - simplejson==3.20.1
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - soupsieve==2.4.1
      - sphinx==6.2.1
      - sphinx-rtd-theme==1.2.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.2
      - tabulate==0.9.0
      - tensorboardx==2.6
      - tensorflow-probability==0.15.0
      - tensorstore==0.1.76
      - terminado==0.17.1
      - text-unidecode==1.3
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - toolz==0.12.0
      - tornado==6.3.2
      - tqdm==4.67.1
      - traitlets==5.9.0
      - trimesh==3.22.0
      - typing-extensions==4.3.0
      - tzdata==2023.3
      - uri-template==1.2.0
      - urllib3==2.0.3
      - virtualenv==20.23.0
      - wandb==0.15.4
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.7
      - wrapt==1.17.2
      - zipp==3.15.0
prefix: /home/tin/anaconda3/envs/mix-me
